easy_admin:
  entities:   
    User:
      class: App\Entity\User
      form:
        fields:
          - username
          - email
          - enabled
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_REDACTEUR' : 'ROLE_REDACTEUR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

    
    Article:
      class: App\Entity\Article
      form:
        fields:
          - title
          - body
    
    ArticleAnswer:
      class: App\Entity\ArticleAnswer
      form:
        fields:
          - body 
  

    
