gos_web_socket:
    server:

        port: 8080         #The port the socket server will listen on
        host: 127.0.0.1      #127.0.0.1    #The host ip to bind to

        
        router:
            resources:
                - '%kernel.project_dir%/config/pubsub_routing.yml'
    topics:
      - app_chat.topic
      - app_matchMaking.topic

    client:
      firewall: main #can be an array of firewalls
      session_handler: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
      
      