liip_imagine:
    # important : si votre serveur est lancé avant l'installation de "gd"S , il faut le redemarrer
    # afin que liipp puisse fonctionner
    # configure resolvers
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    # loaders
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.root_dir%/../public/'
                    
    driver: "gd"

    filter_sets:
        cache: ~

        # note: le nom du filtre est completement customizable
        thumb_profile:
            quality: 80
            filters:
                thumbnail:
                    size: [98, 98]
                    mode: outbound
                background:
                    size: [104, 104]
                    position: center
                    color: '#000000'

        thumb_prestige:
            quality: 80
            filters:
                thumbnail:
                    size: [98, 98]
                    mode: outbound
                background:
                    size: [104, 104]
                    position: center
                    color: '#fbf005'  
        thumb_nav:
            quality: 80
            filters:
                thumbnail:
                    size: [40, 40]
                    mode: outbound
                background:
                    size: [44, 44]
                    position: center
                    color: '#000000'
#liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"
#
#    # define your filter sets under this option
#    filter_sets:
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
#        squared_thumbnail:
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'
