swiftmailer: 
    transport: gmail
    username: super.chess.online@gmail.com
    password: Z4lKvQR2!w
    host: localhost
    port: 465
    encryption: ssl
    auth-mode: login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false