chat_global:
    channel: chat/global 
    handler:
        callback: 'chat.topic' #related to the getName() of your topic


chat_private:
    channel: chat/private
    handler:
        callback: 'chat.topic'

player_topic:
    channel: player
    handler:
        callback: 'player.topic'

match_making:
    channel: matchmaking
    handler:
        callback: 'matchmaking.topic'

game:
    channel: game/{gameId}/{playerOne}/{playerTwo}
    handler:
        callback: 'game.topic'
    requirements:
        playerOne:
            pattern: "[a-z]+"
        playerTwo:
            pattern: "[a-z]+"
        gameId:
            pattern: "\\d+"

invitation:
    channel: invitation
    handler:
        callback: 'invitation.topic'

invitation_channel:
    channel: invitation/{playerOne}/{playerTwo}
    handler:
        callback: 'invitation.topic'
    requirements:
        playerOne:
            pattern: "[a-z]+"
        playerTwo:
            pattern: "[a-z]+"
       
